# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to build and unit test WebApp only - no app or bicep deploy
# ------------------------------------------------------------------------------------------------------------------------
# FYI: You need to set up some secrets before running this workflows - see CreateGitHubSecrets.md for details.
# ------------------------------------------------------------------------------------------------------------------------
name: 2.build.only
run-name: '2 - Build Only by @${{ github.actor }}'

on:
  workflow_dispatch:
    inputs:
      runBuildDeployWeb:
        description: Build and Deploy WebApp
        default: true
        type: boolean
      # runBuildDeployFunction:
      #   description: Build and Deploy Function
      #   default: true
      #   type: boolean
      runMSDevSecOpsScan:
        description: 'Run MS DevSecOps Scan'
        required: false
        default: false
        type: boolean
      runGHASScan:
        description: 'Run GitHub Advanced Security Scan'
        required: false
        default: false
        type: boolean
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 
# ------------------------------------------------------------------------------------------------------------------------
permissions:
  id-token: write
  contents: write
  actions: read
  pages: write
  security-events: write
  checks: write
  issues: read
  pull-requests: read
  packages: read

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  scan-code:
    name: Scan Source Code
    uses: ./.github/workflows/template-scan-code.yml
    secrets: inherit
    if: inputs.runMSDevSecOpsScan || inputs.runGHASScan
    with:
      runMSDevSecOpsScan: ${{ inputs.runMSDevSecOpsScan }}
      runGHASScan: ${{ inputs.runGHASScan }}

# ------------------------------------------------------------------------------------------------------------------------
  build-webapp:
    name: Build WebApp
    uses: ./.github/workflows/template-webapp-build.yml
    if: inputs.runBuildDeployWeb
    secrets: inherit
    with:
      envCode: 'dev'
      rootDirectory: '${{ vars.APP_PROJECT_FOLDER_NAME }}'
      projectName: '${{ vars.APP_PROJECT_NAME }}'
      testDirectory: '${{ vars.APP_TEST_FOLDER_NAME }}'
      testProjectName: '${{ vars.APP_TEST_PROJECT_NAME }}'
      testApplication: true
      listFilesAfterBuild: true

  # build-func:
  #   name: Build Function
  #   if: inputs.runBuildDeployFunction
  #   uses: ./.github/workflows/template-function-app-build.yml
  #   secrets: inherit
  #   with:
  #     envCode: 'dev'
  #     rootDirectory: '${{ vars.FUNC_PROJECT_FOLDER_NAME }}'
  #     projectName: '${{ vars.FUNC_PROJECT_NAME }}'
  #     testDirectory: '${{ vars.FUNC_TEST_FOLDER_NAME }}'
  #     testProjectName: '${{ vars.FUNC_TEST_PROJECT_NAME }}'
  #     testApplication: true
  #     listFilesAfterBuild: true
